M48
; DRILL file {KiCad (5.99.0-9795-gc3c3649211)} date Thu Mar 25 09:38:20 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-03-25T09:38:20-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-9795-gc3c3649211)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T1C0.0236
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T2C0.0248
%
G90
G05
T1
; not plated pad hole
X5.0479Y-1.7676
T2
X5.0479Y-1.7676
X5.2841Y-1.7676
T0
M30
